### ISSUE TITLE
1.0.13 version prints with two v's due to v1.0.13 tag name

### ISSUE THREAD

**Issue by ilovezfs** [Eneco/landscaper#113]
1.0.12 tag is 1.0.12
1.0.13 tag is v1.0.13

So now the version prints as `vv1.0.13` not `v1.0.13`

**Comment by rollulus** [comment]
Thanks, fixed, v1.0.14 is on its way

**Comment by ilovezfs** [comment]
>chore: assume that git tag contains has v prefix

may want to force push out that "contains has"
