### ISSUE TITLE
Landscaper does not work with helm plugin "helm-gcs"

### ISSUE THREAD

**Issue by james-masson** [Eneco/landscaper#117]
I recently tried to switch from a custom-proxy in front of google cloud storage - for hosting my charts - to a helm plugin "helm-gcs" https://github.com/nouney/helm-gcs 

```
JEG-CON-GEL0068:k8s-shared-services-deployer james.masson$ helm repo list
NAME            	URL
stable          	https://kubernetes-charts.storage.googleapis.com
local           	http://127.0.0.1:8879
my-charts	 gs://<redacted>-charts/repo
```
```
JEG-CON-GEL0068:k8s-shared-services-deployer james.masson$ helm plugin list
NAME	VERSION	DESCRIPTION
gcs 	0.1.4  	Manage repositories on Google Cloud Storage
```

The helm plugin works just fine for installing directly with helm.

```
JEG-CON-GEL0068:k8s-shared-services-deployer james.masson$ helm install -n deleteme my-charts/fix-thp --version 0.1.10
NAME:   deleteme
LAST DEPLOYED: Mon Apr  9 14:58:07 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/DaemonSet
NAME     DESIRED  CURRENT  READY  UP-TO-DATE  AVAILABLE  NODE SELECTOR      AGE
fix-thp  0        0        0      0           0          jd.nodepool=redis  0s

```

When I try to do the same thing with landscaper...

```
[2018-04-09T14:57:19+01:00]  INFO This is Landscaper v1.0.14 commit=c3a9ed96177c01491529b0eca7ba1d131a26e8e8 tag=v1.0.14
[2018-04-09T14:57:19+01:00]  INFO Apply landscape desired state dir= dryRun=true environment= helmHome=/Users/james.masson/.helm namespace=default releasePrefix= verbose=false wait=true waitTimeout=5m0s
[2018-04-09T14:57:20+01:00]  INFO Connected to Kubernetes kubernetesVersion=v1.9.2-gke.1
[2018-04-09T14:57:20+01:00]  INFO Connected to Tiller clientServerCompatible=true tillerVersion=v2.8.2
[2018-04-09T14:57:20+01:00]  INFO Obtain desired state from files files=[clusters/helm/dev/kube-system/ip-masq-agent-config.yaml clusters/helm/dev/shared-services/external-dns.yaml clusters/helm/dev/shared-services/nginx-ingress.yaml]
[2018-04-09T14:57:20+01:00] ERROR Loading desired state failed error=cannot resolve chartversion: Could not find protocol handler for: gs
Error: cannot resolve chartversion: Could not find protocol handler for: gs
```

**Comment by james-masson** [comment]
Looks like that Landscaper is calling a helm function that's trying to parse the Chart repo URL - and not liking the "gs" prefix to the URL.

https://github.com/kubernetes/helm/blob/master/pkg/repo/chartrepo.go#L63

Probably not a landscaper bug per-se - either helm-gcs or helm needs to change.

**Comment by rollulus** [comment]
Thanks for reporting, keep us posted whatever the outcome is. I can't recall off the top of my head where this protocol handler / scheme thing gets populated, and if landscaper is supposed to do somewhere.

**Comment by nouney** [comment]
Hi,

I'm the author of helm-gcs. I've just started to investigate on the issue (thanks @james-masson for reporting it).

@rollulus
I don't know Landscraper at all. Does it handle helm plugins? It doesn't look like:

https://github.com/Eneco/landscaper/blob/b5d494b16f3cd5ae2b5b8a2ea9ea4a8e9436790c/pkg/landscaper/chart.go#L64-L74

With an empty environment, `getter.All()` will only return the HTTP getter.  `EnvSettings.Home` has to be manually set.

@james-masson a quick workaround (not tested) could be to set the env var `HELM_PLUGIN`  (see https://github.com/kubernetes/helm/blob/10f880a876d030aab6ee8861c1a6b5f02fcbadd3/pkg/helm/environment/environment.go#L72)

`HELM_PLUGIN=$(helm home)/plugins`

**Comment by james-masson** [comment]
confirmed - using `HELM_PLUGIN=$(helm home)/plugins` fixes the problem.

So, it looks like Landscaper needs to support helm plugins, as it's using helm functions natively.
