### ISSUE TITLE
Latest version: 1.0.14 or 1.0.16

### ISSUE THREAD

**Issue by ilovezfs** [Eneco/landscaper#120]
I cannot tell from https://github.com/Eneco/landscaper/releases

**Comment by rollulus** [comment]
Hi, you're right, the deploy part broke because of how `goreleaser` got installed, but due to the hacky nature of how travis is setup it went unnoticed. Thanks for letting us now.

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by rollulus** [comment]
And it works again... for now :crossed_fingers:

**Comment by ilovezfs** [comment]
Thanks @rollulus! Voilà https://github.com/Homebrew/homebrew-core/pull/27648

**Comment by rollulus** [comment]
And thank you too!
