### ISSUE TITLE
Upgrade to support helm v3

### ISSUE THREAD

**Issue by chenrui333** [Eneco/landscaper#138]
Relates to https://github.com/Homebrew/homebrew-core/pull/47631#issuecomment-563100506

**Comment by rollulus** [comment]
Hi, thanks for the effort. Is anyone still using landscaper?

**Comment by dxlr8r** [comment]
if not landscaper, what are they using?

**Comment by rollulus** [comment]
I have no idea.

**Comment by MMore** [comment]
https://github.com/roboll/helmfile probably.

**Comment by rollulus** [comment]
I hereby declare Landscaper dead. Thanks for everything.
