### ISSUE TITLE
Add component scope limiting filter

### ISSUE THREAD

**Issue by rollulus** [Eneco/landscaper#21]
Convenient if you want to test run something you're working on and ignore the rest of the landscape.

**Comment by andrewstevenson** [comment]
Can we allow grouping into sub folders rather than a flat structure?

**Comment by rollulus** [comment]
As of [v1.0.3](https://github.com/Eneco/landscaper/commit/2a5e7e921caffb0020a94c0e6773ab169db377c5) you can provide file names as program arguments. Using shell expansion one could do e.g. `landscaper */*.yaml`.
