### ISSUE TITLE
Allow greater flexibility in populating Landscaper secrets

### ISSUE THREAD

**Issue by shanesveller** [Eneco/landscaper#43]
Superset of #42. I would love to have pluggable sources for secrets other than environment variables, such as a local file, Hashicorp's Vault, other remote K/V stores like Etcd/Consul, etc. Of course, you could wire up basically any of what I've mentioned to populate env vars with a little glue code, often surprisingly little. But env vars have some trade-offs that prevent them from being some user's first choice for sensitive data, myself included.

**Comment by rollulus** [comment]
Agreed, shane. Actually, the environment based `SecretsProvider` was a place holder until we had Vault in place.

**Comment by rollulus** [comment]
I'll interpret this issue as referring to the flexibility in the code, which was worse than I believed. I'll address that, and keep track of specific secret sources (e.g. files, Vault) via specific issues, e.g. #54. If you have some specific wishes, @shanesveller, please open an issue -- or rather: contribute. Thanks!
