### ISSUE TITLE
Upgrade to Kubernetes 1.6.2 and Helm 2.3.1

### ISSUE THREAD

**Issue by scheetz** [Eneco/landscaper#46]
Any chance this is going to happen?

**Comment by shaneramey** [comment]
I did this myself by updating glide.yaml and following these steps: https://github.com/Eneco/landscaper#from-source

**Comment by scheetz** [comment]
I am not sure how that could have worked for you since some subpackages no longer exist in helm 2.3.1.

[ERROR] Error scanning k8s.io/helm/cmd/helm/downloader: open /home/scheetz/.glide/cache/src/https-k8s.io-helm/cmd/helm/downloader: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.
[ERROR] Error scanning k8s.io/helm/cmd/helm/helmpath: open /home/scheetz/.glide/cache/src/https-k8s.io-helm/cmd/helm/helmpath: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.

**Comment by shaneramey** [comment]
you're right, I was building with the old dependencies - sorry!

**Comment by rollulus** [comment]
@scheetz yes

**Comment by rollulus** [comment]
Helm 2.3.1 itself is on [k8s 1.5.x](https://github.com/kubernetes/helm/blob/32562a3040bb5ca690339b9840b6f60f8ce25da4/glide.yaml#L28). I'll focus on the same combination as well.
