### ISSUE TITLE
Add --no-cache option to apply

### ISSUE THREAD

**Issue by wilreichert** [Eneco/landscaper#47]
provide the ability to not use a cached chart in the event the cached copy is corrupted or re-deploying the same version.

**Comment by rollulus** [comment]
Is that intended to fix a particular problem you experience? See, because of having several problems with Helm's repo/cache, at some point we made Landscaper always download each chart when it is used, which sounds a lot like to behaviour you describe -- if I understand you correctly. Thanks.

**Comment by wilreichert** [comment]
Was testing with helm 2.2.3 & landscaper master & did the following:

helm package'd hello-world - packaged the chart to local repo
landscaper apply  ...  - installed to kube cluster
made small edit to hello-world chart (did not change version) & re-ran helm package & updated local repo
landscaper apply ...  - old chart version used, changes did not appear 

Is it possible to detect chart changes if the version does not change?

**Comment by rollulus** [comment]
Ah I get it now: charts are stored in `os.TempDir()`. On subsequent runs, the chart version must change if the chart changed.

**Comment by rollulus** [comment]
A `rm /tmp/landscaper; landscaper apply ...` should do; or bump your Chart versions. Closing for now, but a fair point anyway. We might add it in the future, please feel free to remind us later (or contribute!). Thanks.
