### ISSUE TITLE
REST api?

### ISSUE THREAD

**Issue by jefflowrey** [Eneco/landscaper#49]
The usage section of landscaper says "Landscaper consists of a core API and a command line interface (CLI) that consumes this API. " 

Is this "core API" exposed through a REST interface? 

Is there a (relatively) easy way to add/create one?

**Comment by rollulus** [comment]
Hi, what we mean is that there is a go package with the core functionality that is consumed by the CLI. At the moment there is no REST interface, and we have no plans to create one. Contributions are welcome, thanks.
