### ISSUE TITLE
Target Helm 2.4.0 + k8s 1.6

### ISSUE THREAD

**Issue by rollulus** [Eneco/landscaper#51]

**Comment by wstrange** [comment]
I am go newbie, but I thought I would fiddle with the glide.yaml dependencies for an hour to see if I could bring them up to date for Kube 1.6.  

Alas, I could not find a combination of deps that would work together.
 
There are related issues on client-go that may be relevant.

**Comment by rollulus** [comment]
Can you give https://github.com/Eneco/landscaper/tree/f_51 a try? I'm not able to give it a try against an actual cluster, but it builds at least. 

And @wstrange, I'm not a Go veteran either, but it wasn't trivial indeed! I had to borrow a serious [hack](https://github.com/kubernetes/helm/blob/master/scripts/setup-apimachinery.sh) from Helm, after I started to wonder how on earth they were able to build something :)

**Comment by wstrange** [comment]
@rollulus  I have not had a chance to test it against a Kube cluster, but I can confirm the build now works, and produces a runnable binary.

Thumbs up!

**Comment by wstrange** [comment]
I tried it out on my cluster today. I am getting an error, but it could be related to my setup:
`~/bin/landscaper apply landscape.yaml
[2017-05-30T09:36:13-06:00]  INFO  This is Landscaper v1.0.4 commit=e98b7c0c39054b01a73bca5471e23b23849eee9b tag=1.0.4-28-ge98b7c0
[2017-05-30T09:36:13-06:00]  INFO  Apply landscape desired state dir= dryRun=false helmHome=/Users/warren.strange/.helm namespace=default releasePrefix=default- verbose=false
[2017-05-30T09:36:13-06:00]  INFO  Connected to Kubernetes kubernetesVersion=v1.6.3
[2017-05-30T09:36:13-06:00]  INFO  Connected to Tiller clientServerCompatible=true tillerVersion=canary+unreleased
[2017-05-30T09:36:13-06:00]  INFO  Obtain desired state from files files=[landscape.yaml]
[2017-05-30T09:36:13-06:00] ERROR  Loading desired state failed error=cannot resolve chartversion: Could not find protocol handler for: https
Error: cannot resolve chartversion: Could not find protocol handler for: https
`

I am pulling the chart from a remote repo on a GS cloud bucket.  (Helm works fine with the chart).

**Comment by rollulus** [comment]
Allight, I'll make time to give it a try myself. The latest minikube wasn't cooperating that well so far for me; once I get access to a 1.6 cluster and feel confident that everything is alright I'll release.

**Comment by rollulus** [comment]
@wstrange can you pull my (amended) commit and retry? I'm quite confident that it works, but just to be sure. Thanks.

**Comment by wstrange** [comment]
I'm getting the same ERROR: as above, but perhaps this is a different issue?

Here is my sample chart:

```
name: test
release:
  chart: forgerock/opendj
  version: 0.2.2
configuration:
  message: Test test

```

That chart is in my remote repo:
```
helm search forgerock/opendj
NAME            	VERSION	DESCRIPTION                               
forgerock/opendj	0.2.2  	Deploy a pair of OpenDJ servers replicated
```

**Comment by rollulus** [comment]
Can you please grab a release from [here](https://github.com/Eneco/landscaper/releases/tag/1.0.5), and give it a try, and give the output with

**Comment by wstrange** [comment]
It worked!

Thanks for your help!

**Comment by rollulus** [comment]
Great, glad to hear, you're welcome :+1:
