### ISSUE TITLE
Landscaper won't run on alpine:3.6

### ISSUE THREAD

**Issue by philipbjorge** [Eneco/landscaper#71]
Curling the latest 1.0.5 binaries for linux amd64 won't run inside the alpine:3.6 image.
It did run in a slim image.

I have a feeling this is because the executable is dynamically linked... Looking into it now.

```
ldd landscaper
	/lib64/ld-linux-x86-64.so.2 (0x559eec9ae000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x559eec9ae000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x559eec9ae000)
```

We were able to resolve this by installing the following on alpine:
```
apk add libc6-compat
```

So basically, this comes down to alpine having muslibc.

------

Would it be possible to start compiling and statically linking against musl?
Are you open to a PR for that?

**Comment by rollulus** [comment]
Hi, thanks for the report. 

Yes, the binaries in the github release are dynamically linked. They are generated by a convenient but not highly configurable thing called [goreleaser](https://github.com/goreleaser/goreleaser). 

For [our](https://hub.docker.com/r/eneco/landscaper/tags/) Docker release of Landscaper, which also bases on alpine, we have the `dockerbinary` make-target that produces a statically linked binary (using `CGO_ENABLED=0`), which is used during the build of the docker image. However, after updating to the latest k8s / Helm yesterday, I realised that I forgot to update the `Dockerfile` (#70), so I cannot say if our Docker image works correctly.

What I gather from skimming through goreleaser's docs is that it allows one to specify  `CGO_ENABLED=0`, but afaik that applies then to _all_ binaries, including the ones that are now dynamically linked (and the darwin targets as well). Outputting a static binary next to the original ones has my preference, but I don't see how.

As I see it now, the easiest way to have a binary readily available online that work in alpine is to do exactly that, at the "cost" of making all binaries statically linked. Adding something like

```yaml
env:
   - CGO_ENABLED=0
```
to the goreleaser config should do.

Any thoughts?

**Comment by philipbjorge** [comment]
I have not worked with Go enough to have an intelligent opinion :)

**Comment by rollulus** [comment]
Well, there is a PR on the way that will result in static binaries, let's see how that works out in practice.

**Comment by rollulus** [comment]
@philipbjorge can you give https://github.com/Eneco/landscaper/releases/tag/1.0.6-rc.1 a try? Works for me on alpine, but just checking.

**Comment by philipbjorge** [comment]
@rollulus -- Works for me!
Thanks

**Comment by rollulus** [comment]
@philipbjorge great, and thanks for letting me know :+1:
