### ISSUE TITLE
Helm dependencies: how do they fit in Landscaper?

### ISSUE THREAD

**Issue by mazzy89** [Eneco/landscaper#87]
If I define a dependencies file `requirements.yaml` under a chart, how does it fit in Landscaper? From my understanding there is no dep management system in Landscaper so at the end it will just fallback to the default value of the chart defined as dependency without any possibility to custom it

**Comment by shaneramey** [comment]
The dependencies are installed along with the parent chart, as the dependencies are packaged under the charts/ directory inside the Helm .tgz file (generated with `helm dependency update && helm package`)

**Comment by rollulus** [comment]
Hope that answers your question, mazzy89. Thanks, @shaneramey . Closing for now.
